version: '3'
services:
    mysql:
      restart: always
      image: "mysql:latest"
      environment:
        MYSQL_DATABASE: 'ct'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - "3307:3306"
      volumes:
        - "/my/own/datadir:/var/lib/mysql"

    phpmyadmin:
      depends_on:
       - mysql
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: mysql

    graphql:
      build: